### ISSUE TITLE
Not displaying all birthdays

### ISSUE THREAD

**Issue by ChrisRG711** [amitchone/MMM-birthdays#1]
Greetings. I have installed and configured MMM-birthdays. It works but based on the way i have configured it. It should be displaying 8 birthdays. But i only see 3. My config is below. Not showing the actual dates in the screenshot . but its showing a few
![image](https://github.com/amitchone/MMM-birthdays/assets/9805053/f79d8459-1ebc-41a3-af2b-1f7acbc7118b)

**Comment by amitchone** [comment]
Hey @ChrisRG711, thanks for letting me know. I will take a look at this tomorrow and get back to you - not entirely sure what's causing this off the top of my head so I'll experiment. Thanks for taking the time to use it and let me know!

**Comment by mirrormonark** [comment]
hello @amitchone  i tried the form, i created a file.json with the birthdays in it.. the first times it was showing and now it just says no birthdays.
i deleted the form and redone but it doesn't change.

**Comment by amitchone** [comment]
@ChrisRG711 I've taken a look - you should find that it _is_ displaying the birthdays - however the opacity of each row decreases beyond the first few, this was a stylistic choice to match the weather forecast module and other similar modules for example. 

Would you be happy with another boolean config option to enable/disable the opacity?

Edit: I should have mentioned that you could verify that all birthdays are indeed listed (just with the opacity decrease) by inspecting the element that contains the birthday list.

**Comment by amitchone** [comment]
@mirrormonark Hi, would you please be able to open another issue with some more information? Here are some useful tips for [debugging the magicmirror](https://gist.github.com/lavolp3/db7de8c0664ba95e8b9247ba685095fe). Thanks!

**Comment by ChrisRG711** [comment]
> @ChrisRG711 I've taken a look - you should find that it _is_ displaying the birthdays - however the opacity of each row decreases beyond the first few, this was a stylistic choice to match the weather forecast module and other similar modules for example.
> 
> Would you be happy with another boolean config option to enable/disable the opacity?

Absolutely

**Comment by amitchone** [comment]
@ChrisRG711 Hey, this is now fixed - off the top of my head I thought it was an opacity issue but it was actually a bug in the calculation (if the birthday is next year it would be missed) but this is now fixed! I've also added the opacity option too. 

Note that `notify_days_after` is no longer supported (as this would clash with setting `notify_days_before` to 365) and I don't think it adds a huge amount of value anyway.

Thanks for raising this issue and I hope it works as you expect now. If you're happy with the fix on the latest main commit then please close this issue.
