### ISSUE TITLE
add traslation italian

### ISSUE THREAD

**Issue by mirrormonark** [amitchone/MMM-birthdays#5]
`{`
    "title": "COMPLEANNI",
    "phrase": {
        "u_m": "{NAME} compierà {AGE} anni tra {DAYS} giorni",
        "u_s": "{NAME} compierà {AGE} anni tra {DAYS} giorno",
        "p_m": "{NAME} ha compiuto {AGE} {DAYS} fa",
        "p_s": "{NAME} ha compiuto {AGE} {DAYS} giorni fa",
        "t": "{NAME} compie {AGE} oggi!"
    }
}``

**Comment by amitchone** [comment]
Thanks for this - I will add it in over the next few days, or feel free to create a PR with this added to the locales folder in the file `it_it.json`

**Comment by amitchone** [comment]
I had 15 minutes so I tested and added it - thanks for the contribution @mirrormonark and I hope this suits your needs!
