### ISSUE TITLE
Add example image directly to the repository

### ISSUE THREAD

**Issue by KristjanESPERANTO** [amitchone/MMM-birthdays#8]
Can you add the example image directly to the repository? For example as `screenshot.png` or `example.png` in any folder :slightly_smiling_face: 

This would have the advantage that the image would be displayed in [the module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I am working on.

**Comment by amitchone** [comment]
Hi Kristjan, thanks for letting me know - I've now done this!

**Comment by KristjanESPERANTO** [comment]
Nice. The screenshot is now displayed in the module list :+1:
