### ISSUE TITLE
NULL header

### ISSUE THREAD

**Issue by jbat66** [amitchone/MMM-birthdays#9]
one; can you add an option, when there is no birthdays the module doesn't show up, and when there is birthdays it shows up with the birthdays.

two; can you make the header optional? Right now if there are no birthdays it shows NULL.
![image](https://github.com/amitchone/MMM-birthdays/assets/80074836/3c74983f-9005-49c3-bc30-e6518d8b4dea)

If I add my own header then I have both my header and the bad NULL header.

![image](https://github.com/amitchone/MMM-birthdays/assets/80074836/26d777ca-7589-4965-af30-db04d0a2bd86)

I love how you laid out the birthdays and how the module works overall. Thank you.

**Comment by jbat66** [comment]
I fixed these issues. I will do a fork, and a pull request later. :-) I need to get outside while it is still nice today and get some non computer things done. lol

**Comment by jbat66** [comment]
I got it forked and updated, here is the pull request:
https://github.com/amitchone/MMM-birthdays/pull/10

**Comment by amitchone** [comment]
Fixed by #10
